camera0: 200
camera1: 204
frame_width: 1280
frame_height: 720
mono_calibration_frames: 1
stereo_calibration_frames: 1
view_resize: 1
checkerboard_box_size_scale: 3.19
checkerboard_rows: 5
checkerboard_columns: 8
cooldown: 30
